### ISSUE TITLE
Command Line Arguments are giving an error "array argument is not an NSArray"

### ISSUE THREAD

**Issue by dmcgill50** [appium/appium-mac2-driver#103]
I am trying to use `'appium:arguments': '--automation true'` and am receiving an error message that the arguments are not an `NSArray`.

```
'appium:serverStartupTimeout': 340000,
'appium:arguments': '--automation true',
```

**Error**

```
Error: [init({"platformName":"mac","bundleId":"com.xyz.abc","appium:serverStartupTimeout":340000,"appium:arguments":"--automation true","showServerLogs":true})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: *** -[NSMutableArray addObjectsFromArray:]: array argument is not an NSArray
```

**Comment by KazuCocoa** [comment]
What about `'appium:arguments': ['--automation true']` or `'appium:arguments': ['--automation', true]`?

**Comment by dmcgill50** [comment]
I no longer receive an error message but the element ids that I expect to be present in the source are not there when launching from the framework. They are there when launching from the command line using `open`.

**Comment by KazuCocoa** [comment]
mac2 WDA launches the app under test via https://github.com/appium/appium-mac2-driver/blob/c474f7e3cfc198480a78f6fcc282b0ffc77cbf85/WebDriverAgentMac/WebDriverAgentLib/Routing/FBSession.m#L88-L102

If your app could launch expectedly only via `open` command, you can launch the app with `open` command by yourself and start an appium session with non-app and non-bundleid capabilities.

**Comment by KazuCocoa** [comment]
Did you check if the `launchArguments` via XCTest worked in your application?
https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch

If this did not work for your app (I mean via XCTest framework), perhaps this launching argument via XCTest framework does not fit your case. If the XCTest framework itself had an issue, only Apple can fix it. (Then, it is worth reporting it to apple then) This mac2 driver itself basically depends on XCTest framework.

I haven't dug in the differences between `open` and via XCTest's launching argument, but they could have sort of differences.

**Comment by dmcgill50** [comment]
I was able to use your workaround of launching in the `beforeEach` but it seems that I will have to close in the `afterEach` since closing the driver has no effect on the AUT. I will create a ticket for our backlog to research this issue in further detail should time allow. If you are or anyone else is able to get another application running with arguments as documented, feel free to update this issue. Appreciate the help.
