### ISSUE TITLE
Updated to Monterey and Xcode 13.1 build. While running automation getting dialog asking password for '"testmanagerd" is trying to enable UI automation'.After giving password its not able to find UI elements .

### ISSUE THREAD

**Issue by Amulyakr** [appium/appium-mac2-driver#104]
mac2driverCalling AppiumDriver.findElement() with args: ["-ios predicate string","label CONTAINS \"Subject: 101121125625test\"","7cd46c61-821d-4164-9d3d-c86bb27e818a"]
[debug] [BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
[debug] [W3C (7cd46c61)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed).

**Comment by KazuCocoa** [comment]
What did the system log say?
Probably it needs to debug.

**Comment by Amulyakr** [comment]
> What did the system log say?
> Probably it needs to debug.

@KazuCocoa Thanks for replying
Where can I find system log??

**Comment by KazuCocoa** [comment]
I guess you can find it in console.app https://www.howtogeek.com/356942/how-to-view-the-system-log-on-a-mac/
I haven't installed Monterey yet, but probably it has.

**Comment by Amulyakr** [comment]
Nov 15 00:47:18 BAN-C02RT38DG8WP syslogd[119]: ASL Sender Statistics
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.cdscheduler" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.install" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.authd" sharing output destination "/var/log/asl" with ASL Module "com.apple.asl".
	Output parameters from ASL Module "com.apple.asl" override any specified in ASL Module "com.apple.authd".
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.authd" sharing output destination "/var/log/system.log" with ASL Module "com.apple.asl".
	Output parameters from ASL Module "com.apple.asl" override any specified in ASL Module "com.apple.authd".
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.authd" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.eventmonitor" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.mail" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.performance" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.iokit.power" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.contacts.ContactsAutocomplete" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.mkb" sharing output destination "/private/var/log/keybagd.log" with ASL Module "com.apple.mkb.internal".
	Output parameters from ASL Module "com.apple.mkb.internal" override any specified in ASL Module "com.apple.mkb".
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.mkb" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.MessageTracer" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 00:47:25 BAN-C02RT38DG8WP syslogd[119]: Configuration Notice:
	ASL Module "com.apple.clouddocs" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Nov 15 02:47:28 BAN-C02RT38DG8WP syslogd[119]: ASL Sender Statistics

**Comment by KazuCocoa** [comment]
I think you can find like the below after "start" the log capture, and stop it. Then, could you copy all of logs and share as GIST? (since the size may be big)
<img width="1207" alt="Screen Shot 2021-11-14 at 23 15 54" src="https://user-images.githubusercontent.com/5511591/141738410-cb2d8942-644d-4062-a6f1-c9ebf41d77ab.png">

**Comment by Amulyakr** [comment]
https://gist.github.com/Amulyakr/301e356be49f54663a2210399efeaa94

**Comment by bumbu** [comment]
Not sure if related, but on CI machines you'll probably want to run `automationmodetool enable-automationmode-without-authentication`
like in https://developer.apple.com/forums/thread/693850

**Comment by KazuCocoa** [comment]
Thanks, I didn't know that...
`automationmodetool` seems not working well on my local env (macOS 12), but I think it is worth to address the command in this readme.
