### ISSUE TITLE
xcode-select was /Library/Developer/CommandLineTools instead of /Applications/Xcode.app/Contents/Developer

### ISSUE THREAD

**Issue by Karthikeyan021298** [appium/appium-mac2-driver#111]
While running the Selenium project using Mac 2 Driver, I am getting the mentioned Error.

Xcode Version-13.2.1

Appium-Server Logs:
[Mac2Driver-Appium-Logs.txt](https://github.com/appium/appium-mac2-driver/files/7844471/Mac2Driver-Appium-Logs.txt)

Eclipse exception
[Mac2Driver-Eclipse-Exception.txt](https://github.com/appium/appium-mac2-driver/files/7844492/Mac2Driver-Eclipse-Exception.txt)

**Comment by KazuCocoa** [comment]
```
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WebDriverAgentMac] [xcodebuild] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[WebDriverAgentMac] Mac2Driver host process has exited with code 1, signal null
```

Did you install Xcode CLI environment? (I guess when you launch Xcode, the CLI env installation also starts to install)

**Comment by Karthikeyan021298** [comment]
I have Installed CLI Tools, Still getting the same issue
[Uploading Mac2Driver_AppiumLogs_After_Downloading_CLITools.txt…]()

**Comment by KazuCocoa** [comment]
What's the result of `xcode-select`?
Possibly you should set xcode as `/Applications/Xcode.app/Contents/Developer`. If not, I guess Apple changed the Xcode path(?)

**Comment by Karthikeyan021298** [comment]
xcode is in the Application section only, but How can I set the Xcode /Applications/Xcode.app/Contents/Developer location?
<img width="288" alt="Screenshot 2022-01-11 at 3 11 04 PM" src="https://user-images.githubusercontent.com/88785130/148919823-abea60dd-7424-4f86-b9f7-ba5a77e1dcdf.png">

**Comment by Karthikeyan021298** [comment]
![Uploading Screenshot 2022-01-11 at 3.19.42 PM.png…]()

**Comment by KazuCocoa** [comment]
Did you run `xcode-select`?
It prints helps, `-p` and `-s`. You can print current Xcode path as CLI and set it.

**Comment by Karthikeyan021298** [comment]
After setting the path of the xcode in the preffered location (/Applications/Xcode.app/Contents/Developer), the issue got resolved, now it is working fine.

Thank you so much Sir !!!!!
