### ISSUE TITLE
Getting error 'WebDriverException : Message: Unhandled endpoint:' when trying to switch to newly opened window

### ISSUE THREAD

**Issue by ArunRajaaSelvarajan** [appium/appium-mac2-driver#115]
Hello,

I am getting an error 'selenium.common.exceptions.WebDriverException: Message: Unhandled endpoint:' when I am trying to switch to a new window, which got opened when selecting 'Login' button in the main window of the application. Whether for mac2 driver we have any different set of commands for switching window ?

**Code:**

from appium.webdriver.common.appiumby import AppiumBy
from appium import webdriver

def step_impl():
    desired_caps = {
        "automationName": "Mac2",
        "platformName": "Mac",
        "bundleId": "com.<test_app>",
        "showServerLogs": True
    }

    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

    login_btn = wait_utils.wait_for_element_to_be_clickable(self, (AppiumBy.XPATH, "//*[@title='Log in']"))
    login_btn.click()

    driver.switch_to.window('<Title of the new window opened>')

Note: I have tried 'handles = driver.window_handles' instead of 'driver.switch_to.window('<Title of the new window opened>')' but still getting the same error.

**StackTrace**
selenium.common.exceptions.WebDriverException: Message: Unhandled endpoint: /session/97B414C3-81DE-46E2-BBF0-0510FA38600E/window -- http://127.0.0.1:10100/ with parameters {
E           wildcards =     (
E               "session/97B414C3-81DE-46E2-BBF0-0510FA38600E/window"
E           );
E       }
E       Stacktrace:
E       UnknownCommandError: Unhandled endpoint: /session/97B414C3-81DE-46E2-BBF0-0510FA38600E/window -- http://127.0.0.1:10100/ with parameters {
E           wildcards =     (
E               "session/97B414C3-81DE-46E2-BBF0-0510FA38600E/window"
E           );
E       }
E           at errorFromW3CJsonCode (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
E           at ProxyRequestError.getActualError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
E           at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:373:25)

../Library/Python/3.10/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py:247: WebDriverException

**Comment by mykola-mokhnach** [comment]
This driver does not have concept of a window. If a "physical" application window is visible in page source (e.g. accessible to XCTest) then it is possible to interact with it. If the window belongs to another app then it is necessary to activate it using https://github.com/appium/appium-mac2-driver#macos-activateapp extension. If the window is still not present then it mist be an XCTest issue, which only Apple is able to address

**Comment by ArunRajaaSelvarajan** [comment]
I was able to perform actions in the new window without switching. Thanks @mykola-mokhnach .Probably I thought too much since I had 2 windows.
