### ISSUE TITLE
How to select a file (aka file handling)

### ISSUE THREAD

**Issue by bumbu** [appium/appium-mac2-driver#119]
Hey, 
Thank you for this amazing driver!

I was looking via the available API, and in WebDriver spec, and can't figure out how to select files. 
My app is using [standalone Open Dialog](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/file-handling/). Should it be interacted with as with a separate app, or is there are way to directly pass in a file location as if done by the file selector?

Thanks!

**Comment by mykola-mokhnach** [comment]
I would try https://developer.apple.com/forums/thread/63275

**Comment by bumbu** [comment]
The above link has worked. Thank you so much for that reference. 
For posterity reasons here's the abstract flow:

* Click on the element that triggers file selector to pop up
* Wait for it to be rendered (I'm checking by accessibility identifier `open-panel`)
* Send `command+shift+g` via the `/session/${sessionId}/wda/keys`
* Wait for GoToFile to show up (I'm checking by accessibility identifiers `open-panel` > `GoToWindow` > `PathTextField` (using a custom framework, hence not sure how exactly it would be represent in appium)
* Send `XCUIKeyboardKeyDelete` (all keys available in [here](https://developer.apple.com/documentation/xctest/xcuikeyboardkey?language=objc))  to delete any contents that may be there
* Type in absolute file path
* Send `XCUIKeyboardKeyEnter`
* Click on Open button (I'm checking by accessibility identifiers `open-panel` > `OKButton`
