### ISSUE TITLE
Unable to locate the Element using DOM Identifier in the XPath.

### ISSUE THREAD

**Issue by Karthikeyan021298** [appium/appium-mac2-driver#121]
Hi,

I have been trying to find the Element using DOM Identifier attribute ( DOM Identifier : 0_simRing)  in the XPath, but it is throwing the "no such element error" in Mac2 driver session. I have attached inspected element details, can you please help me on this.

Thank you,
Karthikeyan
<img width="452" alt="Screenshot 2022-03-12 at 9 57 23 PM" src="https://user-images.githubusercontent.com/88785130/158026462-0ea6dd38-2040-446d-ac9b-ad0b7b433b1a.png">

**Comment by mykola-mokhnach** [comment]
Make sure the destination element is present in the page source returned by the driver. If it is not there then it must be an XCTest issue, which only Apple could address.

**Comment by Karthikeyan021298** [comment]
Thank you for the quick response. Like as you said the destination element is not in the Page source, will try to reach out to  Apple or the coressponding application.
Thank you once again..
