### ISSUE TITLE
Web app in mac

### ISSUE THREAD

**Issue by CarlosNano** [appium/appium-mac2-driver#127]
Hi all

I'm trying to test a web app built with ionic, which is using Chromium in the background.

This are the capabilities I've set up:
```
            caps.setCapability("platformName", "mac");
            caps.setCapability("platformVersion", "12.2.1");
            caps.setCapability("automationName", "mac2");
            caps.setCapability("bundleId", "com.company.id");
```

If I set up this capabilities in the appium inspector, the app will will be launched but I can't inspect anything, even if I change the context. 

Can I use this driver for webapps? if so, Am I missing something?

Thanks

**Comment by CarlosNano** [comment]
So for example in the appium inspector, if I select:
![image](https://user-images.githubusercontent.com/72921935/159909285-35e45942-cbd2-459a-bdc2-3e8e07dc2adc.png)

This area will be selected 

![image](https://user-images.githubusercontent.com/72921935/159909220-a2350029-bd31-4f21-b917-308cd465e600.png)

There is nothing there, there is not a hidden view or anything

**Comment by MikkelIJ** [comment]
Do you get any error like me when you just run appium from terminal ?
https://github.com/appium/appium-mac2-driver/issues/128

**Comment by KazuCocoa** [comment]
This driver does not support WebView context.
This driver works only when the app under test can work with XCTest framework by Apple. (Probably native apps?)

**Comment by CarlosNano** [comment]
Oh that makes sense why it's not working.

Not sure which driver I can use in this case then?

Thanks

**Comment by mykola-mokhnach** [comment]
> Oh that makes sense why it's not working.
> 
> Not sure which driver I can use in this case then?
> 
> Thanks

If the webview provides any possibilities of debugging then it would be theoretically possible to use chromedriver to connect to it and automate using vanilla selenium. Otherwise 🤷

**Comment by KazuCocoa** [comment]
I guess the ionic project address the possibility of testing with existing framework if it could like how to run tests with chromedriver.

**Comment by CarlosNano** [comment]
I guess that means that Appium doesn't support this kind of Apps

Thanks both for the answers,
