### ISSUE TITLE
Cannot find module 'resolve-from'

### ISSUE THREAD

**Issue by MikkelIJ** [appium/appium-mac2-driver#128]
Hello everyone.
I am able to successfully install mac2 driver on appium v2.0.0-beta.27.
But when I run it, I get this error message: **Cannot find module 'resolve-from'**
I also seem to get an error for the Safari driver.
Is this a known issue? 
Can someone help me out here ?
Do I need to provide more info?

❯ node --version
v14.17.1

❯ appium
[Appium] Welcome to Appium v2.0.0-beta.27
[Appium] Attempting to load driver safari...
[Appium] Could not load driver 'safari', so it will not be available. Error in loading the driver was: Cannot find module '/Users/mikman/.appium/node_modules/appium-safari-driver'
[Appium] Require stack:
[Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium] Error: Cannot find module '/Users/mikman/.appium/node_modules/appium-safari-driver'
[debug] [Appium] Require stack:
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[debug] [Appium]     at Function.resolve (internal/modules/cjs/helpers.js:98:19)
[debug] [Appium]     at DriverConfig.require (/usr/local/lib/node_modules/appium/lib/extension/extension-config.js:320:33)
[debug] [Appium]     at map (/usr/local/lib/node_modules/appium/lib/extension/index.js:87:31)
[debug] [Appium]     at Array.map (<anonymous>)
[debug] [Appium]     at getActiveDrivers (/usr/local/lib/node_modules/appium/lib/extension/index.js:84:8)
[debug] [Appium]     at main (/usr/local/lib/node_modules/appium/lib/main.js:264:25)
[Appium] Attempting to load driver mac2...
[debug] [Appium] Requiring driver at /Users/mikman/.appium/node_modules/appium-mac2-driver
[Appium] Could not load driver 'mac2', so it will not be available. Error in loading the driver was: **Cannot find module 'resolve-from'**
[Appium] Require stack:
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/build/lib/npm.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/build/lib/env.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/build/lib/index.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/index.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/protocol/protocol.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/protocol/index.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/index.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/index.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/build/lib/driver.js
[Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/build/index.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium] Error: Cannot find module 'resolve-from'
[debug] [Appium] Require stack:
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/build/lib/npm.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/build/lib/env.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/build/lib/index.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/index.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/protocol/protocol.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/protocol/index.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/build/lib/index.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/base-driver/index.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/build/lib/driver.js
[debug] [Appium] - /Users/mikman/.appium/node_modules/appium-mac2-driver/build/index.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:92:18)
[debug] [Appium]     at Object.<anonymous> (/Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/lib/npm.js:9:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:92:18)
[debug] [Appium]     at Object.<anonymous> (/Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/lib/env.js:7:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:92:18)
[debug] [Appium]     at Object.<anonymous> (/Users/mikman/.appium/node_modules/appium-mac2-driver/node_modules/@appium/support/lib/index.js:15:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - safari@3.1.0 (automationName 'Safari')
[Appium]   - mac2@1.1.3 (automationName 'Mac2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

**Comment by mandutree** [comment]
I was just strugging with this today.  It looks like there was an issue introduced in v1.1.3.  When I downgraded to v1.1.2: `appium driver install mac2@1.1.2`, my problem was solved.

**Comment by KazuCocoa** [comment]
it is probably the version was created with appium support lib 2.56.0.
Let me push a new version to include it.

**Comment by KazuCocoa** [comment]
What about 1.1.4?

**Comment by mandutree** [comment]
It's working for me.  Thanks for the quick turn around!

**Comment by MikkelIJ** [comment]
oh lord, thank you so much for the quick response!
The error is gone now!
