### ISSUE TITLE
[Questions] - Finding elements in QT application

### ISSUE THREAD

**Issue by MikkelIJ** [appium/appium-mac2-driver#130]
I do QA on a QT application for macOS  and Windows.
I have been working on making automated tests with Appium 1.22.0 through WebdriverIO.
The application does not have much support for automation id's or other kinds of labels, however we have had some success with using xpath via the AppiumForMac app, but we still have some issues and that is why I am looking into mac2 driver.

However, after trying out the mac2 driver and following the examples from find-e2e-specs.js

I keep getting errors saying it can not find the element
![image](https://user-images.githubusercontent.com/22520992/160696279-63b88b99-7a32-445e-8c83-1396be54764b.png)

![image](https://user-images.githubusercontent.com/22520992/160696318-02fd1d56-4bbe-42ce-a387-a06f7b1396f7.png)

My questions are.
Is it not possible to find elements using xpath in the format that AppiumForMac give me?

When I use the Accessibility Inspector, I get something like this.
_note: Not the same element as in other screenshot._
![image](https://user-images.githubusercontent.com/22520992/160693058-dcf4e34c-70d2-46da-ae55-8d4023baa6fd.png)

Are there anything here I can use to interact with ??
If so, how should i format it when writing the code ?

If this driver is not the right solution for this application, can you recommend anything else?

**Comment by MikkelIJ** [comment]
When I try to install the previous mac driver I get this error
![image](https://user-images.githubusercontent.com/22520992/160698299-303b898b-d0d8-4518-bc1c-c14e7daec222.png)

**Comment by mykola-mokhnach** [comment]
This driver is based on Apple's XCTest and only supports what the latter does. 

The legacy mac driver is not supported by the Appium team nor it is maintained.
