### ISSUE TITLE
Unable to check focused state of element.

### ISSUE THREAD

**Issue by grokys** [appium/appium-mac2-driver#144]
In Selenium, the recommended way to check if an element is focused is to use:

```
element.equals(driver.switchTo().activeElement());
```

However this does not work using the `appium-mac2-driver` as it appears that it's not possible to compare two elements for equality in appium:

- https://github.com/appium/appium/issues/2404
- https://github.com/appium/appium/issues/9962

Is there a way of doing this currently? If not:

- Would it make sense to expose the focused state as an attribute?
- Should there be a way of comparing elements on the server?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-mac2-driver/pull/145 should do the job

**Comment by grokys** [comment]
Wow, thank you! I didn't expect a reply so quickly, never mind a PR ;) I will get the driver building locally and try this out.
