### ISSUE TITLE
Element with locator not found.

### ISSUE THREAD

**Issue by BISTArk** [appium/appium-mac2-driver#147]
We are trying to automate some flows on a macos app using Robot framework and appium library. We are able to automate the flows for apps like calculator. So, the installation and sever are running well on the machine. But when we run it on our app it gives the following logs (saying the element with the specified locator isnt found).
Any inputs?
[logs.txt](https://github.com/appium/appium-mac2-driver/files/9008339/logs.txt)

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:10100/session/BA087AF5-9B1C-4E3C-8404-8C99D3C4859F/elements] with body: \{"using":"xpath","value":"/AXApplication[@AXTitle='Webex']/AXWindow[@AXTitle='Webex' and @AXIdentifier='main_window' and @AXSubrole='AXStandardWindow']/AXSplitGroup[@AXIdentifier='_NS:82']/AXButton[@AXTitle='Messaging tab' and @AXIdentifier='WTMessagingHubButton' and @AXSubrole='AXTabButton']"\}\

Not sure where such locators are coming from. mac2 driver elements for sure do not support any of the above properties. You could only use attributes and locator strategies that are officially documented: 

https://github.com/appium/appium-mac2-driver#element-location 
https://github.com/appium/appium-mac2-driver#element-attributes
