### ISSUE TITLE
Help Attribute is not getting captured in the Pagesource.

### ISSUE THREAD

**Issue by Karthikeyan021298** [appium/appium-mac2-driver#153]
When I tried to Inspect the Element using Accessibility inspector, I got the "Help" attribute of the element, but when I tried to get the Page source the "Help" Attribute was not there in the Page source.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/88785130/180644972-4930eea0-efb0-4b12-aa99-2a673593ae5b.png">

XCUIElementTypeButton elementType="9" identifier="_NS:543" label="" title="" enabled="true" selected="false" x="634" y="624" width="52" height="52",  this is the value I got from the Pagesource for the Element.

Regards,
Karthikeyan

**Comment by mykola-mokhnach** [comment]
https://developer.apple.com/documentation/xctest/xcuielementattributes?language=objc

These are all attributes that xctest itself provides. If they don't contain the above text then probably there no (official) way to retrieve it using xctest
