### ISSUE TITLE
Cannot perform send keys action

### ISSUE THREAD

**Issue by lcwus2** [appium/appium-mac2-driver#154]
appium v1.22.3

I use inspect tool to locate a text field and want to send the text by sending keys action. Error msg is 
![Screenshot2022_08_04_091021](https://user-images.githubusercontent.com/30100640/182741575-cfe278cd-9af4-4a5c-b1e5-26b46f55657f.jpg)

**Comment by lcwus2** [comment]
and I always met error "Interactions are not available for this element"

**Comment by zhouxihong1** [comment]
可以通过xcui文档中提供的执行脚本的方式，实现点击之后，再输入字符，针对任意控件都能生效，本人有开源了一个基本封装库，在https://github.com/zhouxihong1/mac_automation.git；欢迎交流

**Comment by mykola-mokhnach** [comment]
It is impossible to advice anything on this issue without detailed server logs and environment infos.
