### ISSUE TITLE
How to hide the mask of autotest?

### ISSUE THREAD

**Issue by sunyax12** [appium/appium-mac2-driver#162]
If the macos is more than 12, there is a mask。Is there a way to cancel?
<img width="286" alt="image" src="https://user-images.githubusercontent.com/49855035/191162073-0a8c5279-8a48-44f9-a4e5-bf61e6228cf3.png">

**Comment by sunyax12** [comment]
I want to record the screen, but the mask is redundancy。

**Comment by Anastasia4520** [comment]
do you solve it ?where is these switch?

**Comment by mykola-mokhnach** [comment]
AFAIK there Apple provides no way to remove that overlay
