### ISSUE TITLE
could i get the advice "capabilities" setting?

### ISSUE THREAD

**Issue by dxhyun** [appium/appium-mac2-driver#163]
hello,

I'm setting the capabilities as below and did "Start Session".
but the correct XCUIElement is not visible in the app source.

It only "XCUIElementTypeWindow"

can i get advice that problem?

{
  "platformName": "mac",
  "appium:automationName": "mac2",
  "appium:systemPort": "10110",
  "appium:systemHost": "127.0.0.1",
  "appium:showServerLogs": "false",
  "appium:serverStartupTimeout": "120000",
  "appium:bundleId": "com.keyplatform.test.superb",
  "appium:deviceName": "Mac"
}

**Comment by KazuCocoa** [comment]
Perhaps https://discuss.appium.io/ also helps if someone had experience.
This driver depends on XCTest framework, so one possible case is the app under test is not good for the XCTest framework like WebView or some frameworks.
