### ISSUE TITLE
Possible to connect to the running application by appium mac2?

### ISSUE THREAD

**Issue by nguyenquangtay** [appium/appium-mac2-driver#165]
Hello.
**Context:** due to the requirement, my application is started by script or auto opening after being installed ... (Not from Appium), 
I need to verify something that happens only by the first time (such as welcome text...)

**Desired:** Does anybody know how to connect to the running application? 

Thank you in advance!

**Comment by KazuCocoa** [comment]
Did you try `appium:bundleId`?

> The bundle identifier of the application to automate, for example com.apple.TextEdit.  This is an optional capability. If it is not provided then the session  will be started without an application under test (actually, it will be  Finder). If the application with the given identifier is not installed  then an error will be thrown on session startup. If the application is  already running then it will be moved to the foreground.

https://github.com/appium/appium-mac2-driver#capabilities

https://discuss.appium.io/ may also help for such general questions

**Comment by nguyenquangtay** [comment]
yes, I've tried with the bundle_id
but it closes my current running window, then reopen the new one(this one I can't test something happens at the first time opening, e.g: the welcome text after installed...)
Do you have any other idea?
Thank you!

**Comment by nguyenquangtay** [comment]
Sorry for saying the thank lately!
I'm now able to connect/interact/merge: Appium driver, webdriver and apple script...
once again, thank you all for your support!
