### ISSUE TITLE
does not have a process ID

### ISSUE THREAD

**Issue by Anastasia4520** [appium/appium-mac2-driver#166]
failed log:
2022-10-17 14:15:41.221233+0800 WebDriverAgentRunner-Runner[69580:186796] Launching macOS application via NSWorkspace while sandboxed. Launch arguments and environment variables may be dropped.
/Users/labtest6_1_air/Downloads/appium-mac2-driver-master/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:54: error: -[UITestingUITests testRunner] : Application 'agora.io.JPMac' does not have a process ID
/Users/labtest6_1_air/Downloads/appium-mac2-driver-master/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:54: error: -[UITestingUITests testRunner] : activate application '<XCUIApplicationImpl: 0x600003567450 agora.io.JPMac at /Users/labtest6_1_air/Desktop/JPMac.app>' (current state: Not Running)
    t =   199.95s         Wait for accessibility to load
/Users/labtest6_1_air/Downloads/appium-mac2-driver-master/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:54: error: -[UITestingUITests testRunner] : Application 'agora.io.JPMac' has not loaded accessibility
    t =   259.96s         Setting up automation session
/Users/labtest6_1_air/Downloads/appium-mac2-driver-master/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:54: error: -[UITestingUITests testRunner] : Failed to get automation session for agora.io.JPMac:0: Timed out while requesting automation session for agora.io.JPMac (pid:0).

The app already is opened, the log show 'does not have a process ID',and can't loaded accessibility, so automation can't going
system:10.15.7,xcode: 12.4,just this computer failed, other PC can work

**Comment by mykola-mokhnach** [comment]
This exception is coming from XCTest. Nothing we can do there.
