### ISSUE TITLE
Unable to click on Top menu icons or its submenu items.

### ISSUE THREAD

**Issue by naagf5** [appium/appium-mac2-driver#178]
**CONTEXT:** 
My requirement is to click on Top right icon from available list of icons (I hope we can call it Systemtray in Mac like windows).
When i click on that icon, it will show a menu. I need to click on one of menu items listed.  (example below)
![image](https://user-images.githubusercontent.com/48239988/208825995-2d883418-8766-4a60-855d-99bacd9d707e.png)

**Whats Happening.**
    **Try-01:** I tried to click on the icon with xpath which got from Appium Inspector. The click operation is not failing with no such element present. That means it is able to find the element. The click operation passing but not opennig any menu.

    **TRY-02**
      Since it is able to open menu, I manually opened the menu (By keeping a sleep) and made the Menu Item available. This time i tried to click on the Menu Item (instead of expanding Menu). This time also the click operation passing but nothing happening. 
      
      NOTE: The image is show menu topic i mentioned above. 
      NOTE2: I downloaded the XML from inspector and able to find single item using the XPath i provided.
      
      
      XPATH of ICON present in MenuBar:   xpath=/XCUIElementTypeApplication/XCUIElementTypeMenuBar[2]/XCUIElementTypeStatusItem
      XPATH of Menu Item (both working one relative): 
       //XCUIElementTypeMenuItem[@identifier="act_ShowDetails:"]
         and 
     //XCUIElementTypeApplication/XCUIElementTypeMenuBar[2]/XCUIElementTypeStatusItem/XCUIElementTypeMenu/XCUIElementTypeMenuItem[22]

**Comment by KazuCocoa** [comment]
If you could get the coordinate, https://github.com/appium/appium-mac2-driver#macos-click may help

**Comment by mykola-mokhnach** [comment]
If something could be done without touching the UI then I would prefer that method as more reliable: https://apple.stackexchange.com/questions/402855/how-to-switch-the-keyboard-input-language-from-the-terminal

**Comment by mykola-mokhnach** [comment]
Also AppleScript approach (less reliable though): https://apple.stackexchange.com/questions/300949/how-to-change-the-spelling-language-in-os-x-with-applescript
