### ISSUE TITLE
Typo in package.json->scripts->e2e-test

### ISSUE THREAD

**Issue by pacozaa** [appium/appium-mac2-driver#184]
I see the `e2e-test` in `package.json` is `"e2e-test": "mocha --exit --timeout 10m \"./test/e2e/**/*-specs.js\""`

I tried to run it and it doesn't work. 
So I replace 

`"e2e-test": "mocha --exit --timeout 10m \"./test/e2e/**/*-specs.js\""`

with 

`"e2e-test": "mocha --exit --timeout 10m \"./test/functional/**/*-specs.js\""`

instead.

I can create PR with this ``"e2e-test": "mocha --exit --timeout 10m \"./test/functional/**/*-specs.js\""`

or rename the `functional` folder to `e2e`

**Comment by mykola-mokhnach** [comment]
thanks for reporting that. Yes, please create a PR
