### ISSUE TITLE
Not able to inspect Flutter based Desktop App

### ISSUE THREAD

**Issue by akagupta98** [appium/appium-mac2-driver#186]
I am using appium 2 to automate flutter based desktop apps.
But inspector is not able to identify the elements. Its not showing hierarchy of elements.
]

![image](https://user-images.githubusercontent.com/106066375/215995911-79c8b40b-1874-4884-921c-2e7c5a10a30c.png)

**Comment by jlipps** [comment]
it looks like however flutter assigns accessibility to elements it is doing so in a way that makes individual elements invisible to accessibility. the mac and ios drivers use accessibility to determine the existence of elements. so this is not a problem that this driver can fix. might reach out to the flutter community to see if there's a way to update the flutter app code to ensure accessibility labels are assigned correctly. there's a similar issue with react native where a certain technique ensures container elements don't hide their contained elements.
