### ISSUE TITLE
I would like to ask if there is a previous release version that can support macos10.12 use it

### ISSUE THREAD

**Issue by xiaoyouxiu** [appium/appium-mac2-driver#206]
Since I am currently using esxi6.5, I can only install macos10.12, it is not convenient to upgrade esxi, so I would like to seek help, please tell me if there is a supported version, I hope to get your reply as soon as possible, thank you!

**Comment by KazuCocoa** [comment]
This driver does not support such a version as the dependent XCTest framework's availability. https://github.com/appium/appium-mac-driver might work but we do not maintain that.
