### ISSUE TITLE
Help: How to designate IP and port of WebDriverAgentMac

### ISSUE THREAD

**Issue by pppppino** [appium/appium-mac2-driver#212]
when i start session, appium will run "xcodebuild WebDriverAgentMac.xcodeproj -scheme WebDriverAgentRunner", but it's service is running on "127.0.0.1:10100". 
so I want to know, how to designate ip and port in command line, such as 192.168.12.19:10101

**Comment by KazuCocoa** [comment]
Please try out `appium:systemPort` and `appium:systemHost`

**Comment by pppppino** [comment]
@KazuCocoa , Thanks a lot, I know the method above, but I wanna know how to designate ip and port **by xcodebuild in command line before start the session of appium**, since I wanna use "appium:webDriverAgentMacUrl" (Firstly, start WebDriverAgent, Secondly, start appium session with disignated webDriverAgentMacUrl)

**Comment by pppppino** [comment]
@KazuCocoa Thank you so much, it works!
