### ISSUE TITLE
Hover/Click element is very slow

### ISSUE THREAD

**Issue by raniod** [appium/appium-mac2-driver#22]
When trying to click element both from the appium UI and using the code, I can see the mouse moving very slowly towards the element.

there is a workaround which clicks on the element using its coordinates using the Actions utility but it's not enough.

How can I overcome this issue?

**Comment by raniod** [comment]
[MJSONWP (e2956790)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/e2956790-b0dc-430b-bf84-be2715487014/element/94C8E510-0BB5-4E9E-9D57-707AA530E7C6/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/e2956790-b0dc-430b-bf84-be2715487014/element/94C8E510-0BB5-4E9E-9D57-707AA530E7C6/click] to [POST http://127.0.0.1:10100/session/897B5F70-1A30-4FDE-9E69-EEECC27FAB73/element/94C8E510-0BB5-4E9E-9D57-707AA530E7C6/click] with body: {}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"897B5F70-1A30-4FDE-9E69-EEECC27FAB73"}
[WD Proxy] Replacing sessionId 897B5F70-1A30-4FDE-9E69-EEECC27FAB73 with e2956790-b0dc-430b-bf84-be2715487014
[HTTP] <-- POST /wd/hub/session/e2956790-b0dc-430b-bf84-be2715487014/element/94C8E510-0BB5-4E9E-9D57-707AA530E7C6/click 200 **30282** ms - 76

**Comment by mykola-mokhnach** [comment]
This behaviour is beyond our control. Please report it to Apple
