### ISSUE TITLE
[Help] How to avoid XCTest popup when start appium mac2 driver

### ISSUE THREAD

**Issue by pppppino** [appium/appium-mac2-driver#228]
appium: 2.1.3
mac2: 1.7.4

Below popup appears once a day, which is a big hinder for my CI, Do we have any method to avoid it or just "allow forever"?

![Screenshot2023_09_05_092344](https://github.com/appium/appium-mac2-driver/assets/129264630/7e22bbff-e601-46b3-ad3e-ca9ae4866090)

**Comment by mykola-mokhnach** [comment]
https://developer.apple.com/forums/thread/693850

**Comment by mykola-mokhnach** [comment]
This is also mentioned in [requirements](https://github.com/appium/appium-mac2-driver#requirements)

**Comment by pppppino** [comment]
Thanks a lot, and it works
