### ISSUE TITLE
An error is reported when starting a session using appium inspector. 'GET /status' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed)

### ISSUE THREAD

**Issue by Zhaotiechui888** [appium/appium-mac2-driver#241]
An error is reported when starting a session using appium inspector. Here is some information：

[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Mac","appium:bundleId":"com.itiger.TigerTrade-Mac","appium:deviceName":"Mac","appium:automationName":"Mac2","appium:showServerLogs":"true","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Mac","appium:bundleId":"com.itiger.TigerTrade-Mac","appium:deviceName":"Mac","appium:automationName":"Mac2","appium:showServerLogs":"true","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[debug] [AppiumDriver@ebaa] Calling AppiumDriver.createSession() with args: [{"platformName":"Mac","appium:bundleId":"com.itiger.TigerTrade-Mac","appium:deviceName":"Mac","appium:automationName":"Mac2","appium:showServerLogs":"true","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Mac","appium:bundleId":"com.itiger.TigerTrade-Mac","appium:deviceName":"Mac","appium:automationName":"Mac2","appium:showServerLogs":"true","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [AppiumDriver@ebaa] Event 'newSessionRequested' logged at 1696855513113 (20:45:13 GMT+0800 (中国标准时间))
[Appium] Attempting to find matching driver for automationName 'Mac2' and platformName 'Mac'
[Appium] The 'mac2' driver was installed and matched caps.
[Appium] Will require it at /Users/admin/.appium/node_modules/appium-mac2-driver
[debug] [Appium] Requiring driver at /Users/admin/.appium/node_modules/appium-mac2-driver
[AppiumDriver@ebaa] Appium v2.0.1 creating new Mac2Driver (v1.8.2) session
[AppiumDriver@ebaa] Checking BaseDriver versions for Appium and Mac2Driver
[AppiumDriver@ebaa] Appium's BaseDriver version is 9.3.20
[AppiumDriver@ebaa] Mac2Driver's BaseDriver version is 9.3.20
[debug] [Mac2Driver@5b4c] Creating session with W3C capabilities: {
[debug] [Mac2Driver@5b4c]   "alwaysMatch": {
[debug] [Mac2Driver@5b4c]     "platformName": "Mac",
[debug] [Mac2Driver@5b4c]     "appium:bundleId": "com.itiger.TigerTrade-Mac",
[debug] [Mac2Driver@5b4c]     "appium:deviceName": "Mac",
[debug] [Mac2Driver@5b4c]     "appium:automationName": "Mac2",
[debug] [Mac2Driver@5b4c]     "appium:showServerLogs": "true",
[debug] [Mac2Driver@5b4c]     "appium:newCommandTimeout": 3600,
[debug] [Mac2Driver@5b4c]     "appium:connectHardwareKeyboard": true
[debug] [Mac2Driver@5b4c]   },
[debug] [Mac2Driver@5b4c]   "firstMatch": [
[debug] [Mac2Driver@5b4c]     {}
[debug] [Mac2Driver@5b4c]   ]
[debug] [Mac2Driver@5b4c] }
[Mac2Driver@5b4c] Capability 'showServerLogs' changed from string to boolean. This may cause unexpected behavior
[Mac2Driver@5b4c] The following capabilities were provided, but are not recognized by Appium:
[Mac2Driver@5b4c]   deviceName
[Mac2Driver@5b4c]   connectHardwareKeyboard
[Mac2Driver@5b4c (7c6d0c11)] Session created with session id: 7c6d0c11-9178-436f-8c2a-c8a843606856
[debug] [WebDriverAgentMac] Using bootstrap root: /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac
[debug] [WebDriverAgentMac] Using xcodebuild binary at '/usr/bin/xcodebuild'
[WebDriverAgentMac] There is no need to perform the project cleanup. A fresh install has been detected
[debug] [WebDriverAgentMac] Using 127.0.0.1 as server host
[debug] [WebDriverAgentMac] Using port 10100
[WebDriverAgentMac] Starting Mac2Driver host process: xcodebuild build-for-testing test-without-building -project /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentMac.xcodeproj -scheme WebDriverAgentRunner COMPILER_INDEX_STORE_ENABLE\=NO
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WebDriverAgentMac] [xcodebuild] Command line invocation:
[debug] [WebDriverAgentMac] [xcodebuild] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentMac.xcodeproj -scheme WebDriverAgentRunner COMPILER_INDEX_STORE_ENABLE=NO
[debug] [WebDriverAgentMac] 
[debug] [WebDriverAgentMac] User defaults from command line:
[debug] [WebDriverAgentMac]     IDEPackageSupportUseBuiltinSCM = YES
[debug] [WebDriverAgentMac] 
[debug] [WebDriverAgentMac] Build settings from command line:
[debug] [WebDriverAgentMac]     COMPILER_INDEX_STORE_ENABLE = NO
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WebDriverAgentMac] [xcodebuild] 2023-10-09 20:45:17.896 xcodebuild[21652:1771052] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-18212/IDEFoundation/Testing/IDETestRunSpecificationBuilder.m:678
[debug] [WebDriverAgentMac] Details:  Failed to compute path to baseline file during test run spec construction: <XCTHTestRunSpecification: 0x7fafd7ba7f50>
[debug] [WebDriverAgentMac] Object:   <IDETestRunSpecificationBuilder>
[debug] [WebDriverAgentMac] Method:   +testRunSpecificationsForTestingSpecifiers:scheme:buildables:withBuildParameters:additionalEnvironmentVariables:additionalCommandLineArguments:testRerunPolicy:includeClangProfileParameters:shouldDebugAppExtensions:error:
[debug] [WebDriverAgentMac] Thread:   <NSThread: 0x7fafd3b04fd0>{number = 1, name = main}
[debug] [WebDriverAgentMac] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[debug] [WebDriverAgentMac] [xcodebuild] note: Using new build system
[debug] [WebDriverAgentMac] [xcodebuild] note: Building targets in parallel
[debug] [WebDriverAgentMac] [xcodebuild] note: Planning build
[debug] [WebDriverAgentMac] [xcodebuild] note: Analyzing workspace
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WebDriverAgentMac] [xcodebuild] note: Using build description from disk
[debug] [WebDriverAgentMac] [xcodebuild] note: Build preparation complete
[debug] [WebDriverAgentMac] [xcodebuild] CompileC /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/Objects-normal/x86_64/WebDriverAgentRunner.o /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'WebDriverAgentRunner' from project 'WebDriverAgentMac')
[debug] [WebDriverAgentMac]     cd /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac
[debug] [WebDriverAgentMac]     export LANG\=en_US.US-ASCII
[debug] [WebDriverAgentMac]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-macos10.15 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path\=/Users/admin/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/admin/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wquoted-include-in-framework-header -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/WebDriverAgentRunner-generated-files.hmap -I/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/WebDriverAgentRunner-own-target-headers.hmap -I/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/WebDriverAgentRunner-all-non-framework-target-headers.hmap -ivfsoverlay /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/all-product-headers.yaml -iquote /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/WebDriverAgentRunner-project-headers.hmap -I/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Products/Debug/include -I/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/DerivedSources-normal/x86_64 -I/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/DerivedSources/x86_64 -I/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/DerivedSources -F/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Products/Debug -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -MMD -MT dependencies -MF /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/Objects-normal/x86_64/WebDriverAgentRunner.d --serialize-diagnostics /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/Objects-normal/x86_64/WebDriverAgentRunner.dia -c /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m -o /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/Objects-normal/x86_64/WebDriverAgentRunner.o
[debug] [WebDriverAgentMac] [xcodebuild] /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:44:81: error: property 'nonStrictOptions' not found on object of type 'XCTExpectedFailureOptions'
[debug] [WebDriverAgentMac]   XCTExpectFailureWithOptions(@"Ignore all failures", XCTExpectedFailureOptions.nonStrictOptions);
[debug] [WebDriverAgentMac]                                                                                 ^
[debug] [WebDriverAgentMac] [xcodebuild] 1 error generated.
[debug] [WebDriverAgentMac] [xcodebuild] ** TEST BUILD FAILED **
[debug] [WebDriverAgentMac] 
[debug] [WebDriverAgentMac] 
[debug] [WebDriverAgentMac] The following build commands failed:
[debug] [WebDriverAgentMac] 	CompileC /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Build/Intermediates.noindex/WebDriverAgentMac.build/Debug/WebDriverAgentRunner.build/Objects-normal/x86_64/WebDriverAgentRunner.o /Users/admin/.appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[debug] [WebDriverAgentMac] (1 failure)
[debug] [WebDriverAgentMac] [xcodebuild] 2023-10-09 20:45:18.974 xcodebuild[21652:1771052] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-18212/IDEFoundation/Testing/IDETestRunSpecificationBuilder.m:678
[debug] [WebDriverAgentMac] Details:  Failed to compute path to baseline file during test run spec construction: <XCTHTestRunSpecification: 0x7fafd7ac5bb0>
[debug] [WebDriverAgentMac] Object:   <IDETestRunSpecificationBuilder>
[debug] [WebDriverAgentMac] Method:   +testRunSpecificationsForTestingSpecifiers:scheme:buildables:withBuildParameters:additionalEnvironmentVariables:additionalCommandLineArguments:testRerunPolicy:includeClangProfileParameters:shouldDebugAppExtensions:error:
[debug] [WebDriverAgentMac] Thread:   <NSThread: 0x7fafd3b04fd0>{number = 1, name = main}
[debug] [WebDriverAgentMac] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WebDriverAgentMac] [xcodebuild] *** If you believe this error represents a bug, please attach the result bundle at /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Logs/Test/Test-WebDriverAgentRunner-2023.10.09_20-45-17-+0800.xcresult
[debug] [WebDriverAgentMac] [xcodebuild] 2023-10-09 20:45:19.441 xcodebuild[21652:1771052] [MT] IDETestOperationsObserverDebug: 0.325 elapsed -- Testing started completed.
[debug] [WebDriverAgentMac] [xcodebuild] 2023-10-09 20:45:19.441 xcodebuild[21652:1771052] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[debug] [WebDriverAgentMac] 2023-10-09 20:45:19.441 xcodebuild[21652:1771052] [MT] IDETestOperationsObserverDebug: 0.325 sec, +0.325 sec -- end
[debug] [WebDriverAgentMac] [xcodebuild] Test session results, code coverage, and logs:
[debug] [WebDriverAgentMac] 	/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Logs/Test/Test-WebDriverAgentRunner-2023.10.09_20-45-17-+0800.xcresult
[debug] [WebDriverAgentMac] [xcodebuild] Testing failed:
[debug] [WebDriverAgentMac] 	Property 'nonStrictOptions' not found on object of type 'XCTExpectedFailureOptions'
[debug] [WebDriverAgentMac] 	WebDriverAgentRunner:
[debug] [WebDriverAgentMac] 		WebDriverAgentRunner-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-aauspsgguhyahggtdgmlcoaoxbqz/Logs/Test/Test-WebDriverAgentRunner-2023.10.09_20-45-17-+0800.xcresult. (Underlying Error: Could not launch “WebDriverAgentRunner”. The executable is missing. Please check your project settings and ensure that they produce a valid product. (Underlying Error: The operation couldn’t be completed. (OSStatus error -10827.))))
[debug] [WebDriverAgentMac] 
[debug] [WebDriverAgentMac] ** TEST EXECUTE FAILED **
[debug] [WebDriverAgentMac] [xcodebuild] Testing started
[WebDriverAgentMac] Mac2Driver host process has exited with code 65, signal null
[WebDriverAgentMac] Mac2Driver session cannot be stopped, because the server is not running
[debug] [AppiumDriver@ebaa] Event 'newSessionStarted' logged at 1696855520184 (20:45:20 GMT+0800 (中国标准时间))
[debug] [AppiumDriver@ebaa] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: 'GET /status' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed). Check the Appium log for more details
[debug] [AppiumDriver@ebaa]     at WDAMacServer.isProxyReady (/Users/admin/.appium/node_modules/appium-mac2-driver/lib/wda-mac.js:316:15)
[debug] [AppiumDriver@ebaa]     at waitMs (/Users/admin/.appium/node_modules/appium-mac2-driver/lib/wda-mac.js:412:44)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:221:20)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at spin (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:231:14)
[debug] [AppiumDriver@ebaa]     at waitForCondition (/Users/admin/.appium/node_modules/appium-mac2-driver/node_modules/asyncbox/lib/asyncbox.js:238:10)
[debug] [AppiumDriver@ebaa]     at WDAMacServer.startSession (/Users/admin/.appium/node_modules/appium-mac2-driver/lib/wda-mac.js:412:9)
[debug] [AppiumDriver@ebaa]     at Mac2Driver.createSession (/Users/admin/.appium/node_modules/appium-mac2-driver/lib/driver.js:110:7)
[debug] [AppiumDriver@ebaa]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:352:35)

**Comment by mykola-mokhnach** [comment]
I cannot reproduce the issue locally. What are your environment details?

**Comment by mykola-mokhnach** [comment]
Also this particular property has only been added in Xcode 13, so make sure it is up to date: https://developer.apple.com/documentation/xctest/xctexpectedfailureoptions/3784636-nonstrictoptions

**Comment by Zhaotiechui888** [comment]
> 我无法在本地重置该问题。您的环境详细信息是什么？

macos Big Sur 11.3.1
xcode 12.5.1
Appium v2.0.1

thanks！Do you need any other environmental information?

**Comment by Zhaotiechui888** [comment]
> 此外，此特定属性仅在 Xcode 13 中添加，因此请确保它是最新的：[https ://developer.apple.com/documentation/xctest/xctexpectedfailureoptions/3784636-nonstrictoptions](https://developer.apple.com/documentation/xctest/xctexpectedfailureoptions/3784636-nonstrictoptions)

Do I need to upgrade to Xcode 13 + to use it?

**Comment by Zhaotiechui888** [comment]
![image](https://github.com/appium/appium-mac2-driver/assets/147405128/b7fa20a5-fb86-4271-bdf5-35c12f6b224b)

Looking at the source code, the error should be caused by this code. I will upgrade XCODE to 13 + first and give it a try
