### ISSUE TITLE
Support of multi windowed applications

### ISSUE THREAD

**Issue by LykashevichAndrei** [appium/appium-mac2-driver#255]
Hello, on my current SUT i need to test multi-windowed application.
So, running i try to switch between current windows, and on the step when i retrieve window_handles i see error

```
UnknownCommandError: Unhandled endpoint: /session/8470FB2D-6F59-4B9F-AC10-78FE9208BF05/window/handles -- 
http://127.0.0.1:10100/ with parameters {
    wildcards =     (
        "session/8470FB2D-6F59-4B9F-AC10-78FE9208BF05/window/handles"
    );
}
```

looks like this functionality is not supported yet.

Can someone assist me here and find a workaround for that.

Appium + Mac2Driver + Python

**Comment by MagdelineNg** [comment]
Hi, did you find a workaround to detect the second window?

**Comment by jonko0493** [comment]
@MagdelineNg all elements in multi-window applications are accessible through [class chain rules](https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules)! no need to switch between windows/dialogs
