### ISSUE TITLE
WKWebView is not supported

### ISSUE THREAD

**Issue by raniod** [appium/appium-mac2-driver#26]

**Comment by mykola-mokhnach** [comment]
It was never intended to be supported

**Comment by Jiurong-Yang** [comment]
Does this driver not intend to support webviews for native Mac applications?

**Comment by KuthorX** [comment]
> It was never intended to be supported

Could you explain why? Does it need Apple's official support, or it's impossible?

**Comment by KazuCocoa** [comment]
We haven't investigated the way. This repository is https://github.com/appium/WebDriverAgent for macOS, so it does not have WebView support.

Current our https://github.com/appium/appium-remote-debugger for WebView in iOS is only for iPhone/iPad platforms. Anyone who interested in can try it for macOS as a new repository. I don't know it's possible yet.

I hope safaridriver by Apple will officially support WebView for macOS/iOS
