### ISSUE TITLE
How to pull up the macbook terminal in windows and execute the command?

### ISSUE THREAD

**Issue by zhaoyanwusheng** [appium/appium-mac2-driver#286]
How do I do the following?
1. Start the Appium service on Windows.
2. Start the WDA service on the MacBook.
3. How to pull up the macbook terminal in windows and execute the command?

**Comment by jlipps** [comment]
Appium and this driver need to be running on the Macbook. Then you can simply connect via a client script (from your windows machine) to the Macbook's host IP and the Appium port when you construct the driver.
