### ISSUE TITLE
elements lookup Xpath strategy

### ISSUE THREAD

**Issue by MagdelineNg** [appium/appium-mac2-driver#290]
What page source API is used by the Mac2 driver to generate the XML tree? For each MacOS app, is the XML generated from the existing HTML used to build the app? I am asking as I want to improve the XPath selectors used by my app (to be more specific, since certain elements lack unique attributes like title/value) but am not sure how the XML tree is currently being generated and found by Mac2 driver

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-mac2-driver/blob/master/WebDriverAgentMac/WebDriverAgentLib/Utilities/FBXPath.m has all the logic
https://github.com/appium/appium-mac2-driver/tree/master?tab=readme-ov-file#element-location describes to what xctest attributes different locators are mapped
