### ISSUE TITLE
Which driver should I use to test a desktop flutter application?

### ISSUE THREAD

**Issue by krasetm12** [appium/appium-mac2-driver#306]
@KazuCocoa
<img width="1298" alt="Screenshot 2024-07-03 at 17 23 58" src="https://github.com/appium/appium-mac2-driver/assets/89021443/f664a7cb-0c2f-4955-a5d4-69743072a26c">

When using mac2driver the desktop flutter application does not respond

**Comment by KazuCocoa** [comment]
Flutter driver does not support macOS yet. https://github.com/appium/appium-flutter-driver/issues/326
