### ISSUE TITLE
Question about shell command support over appium

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium-mac2-driver#34]
Hello, I was wondering if this incarnation will consider the ability to send shell command through appium. I understand that this is considered a "security risk" but as mentioned before for the first version of this driver, one can automate the shell program to do the same sort of thing.

I'm just wondering to plan for eventual incorporation of this driver in our code base.

**Comment by mykola-mokhnach** [comment]
There is a possibility to run Apple Scripts: https://github.com/appium/appium-mac2-driver#applescript-commands-execution. The driver also exposes `prerun` and `postrun` capabilities to run Apple script on session startup and on termination.

We don't plan to add more on top of that.
