### ISSUE TITLE
How to press Enter key

### ISSUE THREAD

**Issue by meskmanz** [appium/appium-mac2-driver#46]
Hi guys,

Excuse me if my question is quite simple or maybe stupid.
How can I press Enter key? I spent a few hours and didn't figure it out. 
 I'm using Java and in appium-for-mac it was pretty simple. I was using .sendKeys(Keys.ENTER)
As I see in appium-mac2-driver I should use macos: keys but I don't understand how to use it in Java.
I saw your python example for custom keys on the page:
edit_field.execute_script('macos: keys', {
        'keys': [{
            'key': 'h',
            'modifierFlags': flagsShift,
        }, {
            'key': 'i',
            'modifierFlags': flagsShift,
        }]
    })

but I cannot adopt it for Java.

Looking forward to your advice!

**Comment by KazuCocoa** [comment]
It is like `mobile:` command in mobile automation.
https://appiumpro.com/editions/3-running-arbitrary-adb-commands-via-appium might help.

https://discuss.appium.io/ also may help to ask such syntax stuff.

**Comment by pramodl7713** [comment]
@meskmanz  , Did you get solution for this , i am also facing same issue , please let me know if you have got the solution,
I want to Press "Enter" Key in Appium for mac for one of the desktop application.

Thanks

**Comment by meskmanz** [comment]
> @meskmanz , Did you get solution for this , i am also facing same issue , please let me know if you have got the solution,
> I want to Press "Enter" Key in Appium for mac for one of the desktop application.
> 
> Thanks

Here is my solution using Java:
Map<String, String> map = new HashMap();
map.put("key", "\n");
List<Map> keys = Arrays.asList(map);
Map<String, Object> arg = ImmutableMap.of("keys", keys);
((RemoteWebDriver) DriverFactory.nativeApp2Driver).executeScript("macos: keys",arg);

**Comment by pramodl7713** [comment]
@meskmanz
Thanks for the solution, anyhow while using -- ((RemoteWebDriver) DriverFactory.nativeApp2Driver).  Iam getting error.
In place of nativeApp2Driver  i have used my mac driver but it giving error saying --macdriver cannot be resolved or is not a field.
