### ISSUE TITLE
Application is not launching: 

### ISSUE THREAD

**Issue by sumanth449** [appium/appium-mac2-driver#49]
The log is:

[HTTP] Waiting until the server is closed
[HTTP] Received server close event
[Appium] Welcome to Appium v1.20.0
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"Calculator","automationName":"mac2","platformName":"mac","showServerLogs":"true"},"capabilities":{"firstMatch":[{"appium:app":"Calculator","appium:automationName":"mac2","platformName":"mac","showServerLogs":"true"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"Calculator","automationName":"mac2","platformName":"mac","showServerLogs":"true"},null,{"firstMatch":[{"appium:app":"Calculator","appium:automationName":"mac2","platformName":"mac","showServerLogs":"true"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1610949306546 (11:25:06 GMT+0530 (India Standard Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   showServerLogs
[Appium] Appium v1.20.0 creating new Mac2Driver (v0.8.1) session
[Appium] Applying relaxed security to 'Mac2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "mac",
[BaseDriver]     "appium:showServerLogs": "true",
[BaseDriver]     "appium:app": "Calculator",
[BaseDriver]     "appium:automationName": "mac2"
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Capability 'showServerLogs' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   app
[BaseDriver] Session created with session id: 9592a4c9-961a-420d-bfc8-09a856765b13
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"version":"Version 10.15.7 (Build 19H114)"},"ready":true,"build":{"time":"Jan 18 2021 11:17:13"}},"sessionId":null}
[WebDriverAgentMac] The host process has already been listening. Proceeding with session creation
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:10100/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac","showServerLogs":true,"app":"Calculator","automationName":"mac2"}}}
[WD Proxy] Got response with status 200: {"value":{"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46","capabilities":{"CFBundleIdentifier":"com.apple.finder"}},"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[Appium] New Mac2Driver session created successfully, session 9592a4c9-961a-420d-bfc8-09a856765b13 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1610949306556 (11:25:06 GMT+0530 (India Standard Time))
[W3C (9592a4c9)] Cached the protocol value 'W3C' for the new session 9592a4c9-961a-420d-bfc8-09a856765b13
[W3C (9592a4c9)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"mac","showServerLogs":true,"app":"Calculator","automationName":"mac2"}}
[HTTP] <-- POST /wd/hub/session 200 11 ms - 165
[HTTP] 
[HTTP] --> GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] {}
[W3C (9592a4c9)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13' to command name 'getSession'
[WD Proxy] Proxying [GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13] to [GET http://127.0.0.1:10100/session/C98989A7-8A46-404A-9824-7D0F29021B46] with no body
[WD Proxy] Got response with status 200: {"value":{"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46","capabilities":{"CFBundleIdentifier":"com.apple.finder"}},"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46"}
[WD Proxy] Replacing sessionId C98989A7-8A46-404A-9824-7D0F29021B46 with 9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] <-- GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13 200 3 ms - 170
[HTTP] 
[HTTP] --> GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] {}
[W3C (9592a4c9)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13' to command name 'getSession'
[WD Proxy] Proxying [GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13] to [GET http://127.0.0.1:10100/session/C98989A7-8A46-404A-9824-7D0F29021B46] with no body
[WD Proxy] Got response with status 200: {"value":{"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46","capabilities":{"CFBundleIdentifier":"com.apple.finder"}},"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46"}
[WD Proxy] Replacing sessionId C98989A7-8A46-404A-9824-7D0F29021B46 with 9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] <-- GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13 200 3 ms - 170
[HTTP] 
[HTTP] --> GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] {}
[W3C (9592a4c9)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13' to command name 'getSession'
[WD Proxy] Proxying [GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13] to [GET http://127.0.0.1:10100/session/C98989A7-8A46-404A-9824-7D0F29021B46] with no body
[WD Proxy] Got response with status 200: {"value":{"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46","capabilities":{"CFBundleIdentifier":"com.apple.finder"}},"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46"}
[WD Proxy] Replacing sessionId C98989A7-8A46-404A-9824-7D0F29021B46 with 9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] <-- GET /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13 200 3 ms - 170
[HTTP] 
[HTTP] --> POST /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13/timeouts
[HTTP] {"implicit":5000}
[W3C (9592a4c9)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13/timeouts' to command name 'timeouts'
[Protocol Converter] Will send the following request bodies to /timeouts: [{"implicit":5000}]
[WD Proxy] Proxying [POST /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13/timeouts] to [POST http://127.0.0.1:10100/session/C98989A7-8A46-404A-9824-7D0F29021B46/timeouts] with body: {"implicit":5000}
[WD Proxy] Got response with status 200: {"value":null,"sessionId":"C98989A7-8A46-404A-9824-7D0F29021B46"}
[WD Proxy] Replacing sessionId C98989A7-8A46-404A-9824-7D0F29021B46 with 9592a4c9-961a-420d-bfc8-09a856765b13
[HTTP] <-- POST /wd/hub/session/9592a4c9-961a-420d-bfc8-09a856765b13/timeouts 200 3 ms - 65
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '9592a4c9-961a-420d-bfc8-09a856765b13' from our master session list
[WD Proxy] Matched '/session/C98989A7-8A46-404A-9824-7D0F29021B46' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /session/C98989A7-8A46-404A-9824-7D0F29021B46] to [DELETE http://127.0.0.1:10100/session/C98989A7-8A46-404A-9824-7D0F29021B46] with no body
[WD Proxy] Got response with status 200: {"value":null,"sessionId":null}

**Comment by sumanth449** [comment]
For automation testing with Eclipse IDE. 


Desired capabilities is :

public class Sample {

	private static AppiumDriver driver;
	public static void main(String[] args) throws IOException, Exception {
		DesiredCapabilities caps = new DesiredCapabilities();

		caps.setCapability("platformName", "mac");

		caps.setCapability("automationName", "mac2");

		caps.setCapability("app", "Calculator");
		caps.setCapability("showServerLogs", "true");
		driver = new AppiumDriver(new URL("http://localhost:4723/wd/hub"), caps);
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		Thread.sleep(4000);
			
	}

}

**Comment by KazuCocoa** [comment]
Please specify `appium:bundleId` instead of `app`. I think your environment launched Finder 
https://github.com/appium/appium-mac2-driver#capabilities
> This is an optional capability. If it is not provided then the session will be started without an application under test (actually, it will be Finder).
