### ISSUE TITLE
Ability to precompile driver binary

### ISSUE THREAD

**Issue by bumbu** [appium/appium-mac2-driver#54]
Wanted first to say thanks for the great library!
It was interesting to learn that appium-mac2-driver has both the JS and the binary all in one, and it took a while to fully grasp the need of xcode on the machine (so we can compile and start the driver).
This works great when just setting up as you don't need to install a separate app, but the downside is that:
* you need xcode on the machine
* first time building the binary may take quite some time (I observed 1-5 minutes delay). 

Hence I was wondering if it would be possible to precompile the binary and use it instead. I tried build the WebDriverAgentRunner, but when I try to start it - it fails with
```
/Users/myuser/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-blmjlygeetmlrueyyykrtouhxqib/Build/Products/Debug/WebDriverAgentRunner-Runner.app/Contents/MacOS/WebDriverAgentRunner-Runner ; exit;
dyld: Library not loaded: @rpath/CoreSymbolicationDT.framework/Versions/A/CoreSymbolicationDT
  Referenced from: /Users/myuser/Library/Developer/Xcode/DerivedData/WebDriverAgentMac-blmjlygeetmlrueyyykrtouhxqib/Build/Products/Debug/WebDriverAgentRunner-Runner.app/Contents/Frameworks/XCTest.framework/Versions/A/XCTest
  Reason: image not found
[1]    33333 abort 
```

It seems like it should be possible to configure the project so that it can be compiled as a stand-alone utility, but that out of my knowledge. And before I spend more time on trying to make it work, it would be great to:
* first understand if it is even possible?
* if it is possible - any hints on how to make it run standalone?

If I get the standalone binary, I know what JS code to change to make it work, so the binary is really the blocker.

I appreciate any help on this, thanks!

**Comment by KazuCocoa** [comment]
> first understand if it is even possible?

Technically possible. https://fbidb.io/docs/test-execution may be a hint to do it.
In general, `xcodebuild` launches MacWDA as XCTest process to connect to `testmanagerd`. Using `xcodebuild` is the easiest, but you can launch the MacWDA via like `idb` tool.

> if it is possible - any hints on how to make it run standalone?

Once you build the MacWDA, you can launch the built module ` file using `xcodebuild test-without-testing`.
Probably You can see xcodebuild command log in the mac2 appium log. The log has `xcodebuild build-for-testing test-without-testing xxxxx`. You can simply remove the `build-for-testing`.
Then, `appium:webDriverAgentMacUrl` capability should help to attach to the running MacWDA from appium.
https://github.com/appium/appium-mac2-driver

**Comment by mykola-mokhnach** [comment]
^ s/test-without-testing/test-without-building/g

**Comment by bumbu** [comment]
Thank you @KazuCocoa and @mykola-mokhnach . I'll write back if I get ahywhere
