### ISSUE TITLE
bundleId change

### ISSUE THREAD

**Issue by puresk** [appium/appium-mac2-driver#61]
Hi, i have test where my bundleId change during test.

My question: 
1) Is there a way to change bundleId when driver is initialized?  
2) Do i have to create new driver? That means, quit one driver, open new with new bundleID (which i don't like as solution, cause it will affect all my pageObjects). 

Thx.

**Comment by KazuCocoa** [comment]
> 1

Do you mean you want to change the bundled of the app under test? (Not WDAMac)
Then, no.


> 2

You can keep running WDAMac with `appium:webDriverAgentMacUrl` capability.

**Comment by puresk** [comment]
Hi, thanks for answer @KazuCocoa. I will try to describe my problem better. I am using Java and Appium.
1. Start appium server
2. Install tested mac app
3. Create appium Driver with -> bundleID = exampleBundleId1
4. Login to app and do setup of app (still same bundleId)
5. After login, app reopens and my app now have different bundleId = exampleBundleId2

From point 5. i can't do anything with app, since driver was created with bundleId = exampleBundleId1

Here is my code: 

```
        caps.setCapability("platformName", "mac");
        caps.setCapability("automationName", "mac2");
        caps.setCapability("deviceName", "Mac");
        caps.setCapability("bundleId", "exampleBundleId1");
        caps.setCapability("newCommandTimeout", 3000);
        new AppiumDriver(new URL(SERVER_URL), caps);
```
So i want to be able to change capabilities (bundleId) of already created driver or find a way to be able to handle mentioned case.

**Comment by DmitryMishtal** [comment]
I do not understand how bundle id can be in real time but maybe command "macos: activateApp" can help with this? (this command is described in main doc https://github.com/appium/appium-mac2-driver)

**Comment by KazuCocoa** [comment]
Okay, then, you can use activateApp Dmitry (thanks) to achieve _After login, app reopens and my app now have different bundleId = exampleBundleId2_

**Comment by puresk** [comment]
@KazuCocoa Thanks! I will try that :-)

**Comment by puresk** [comment]
Hey, i just wanted to let you know that it worked! :-) Thx again.
