### ISSUE TITLE
need a environment configuration guide for appium-mac2-driver+nodejs+javascript

### ISSUE THREAD

**Issue by id0ma1no** [appium/appium-mac2-driver#67]
Hi:
       i'm using appium-mac2-driver with nodejs + javascrpt to write an automation test tool on mac, here is my os information: macOS Big Sur v11.1 + node v14.16.0 + npm v6.14.11, and my installed npm dependencies were like below:
/usr/local/lib
├── @babel/core@7.13.10
├── appium-base-driver@7.5.1
├── appium-gulp-plugins@5.5.0
├── appium-mac2-driver@0.12.0
├── chai@4.3.4
├── chai-as-promised@7.1.1
├── electron@12.0.1
├── eslint-config-appium@4.7.0
├── gulp@4.0.2
├── mocha@8.3.2
├── mochawesome@6.2.2
├── mysql@2.18.1
├── npm@6.14.11
├── portscanner@2.2.0
├── pre-commit@1.2.2
├── selenium@2.20.0
├── sinon@9.2.4
├── teen_process@1.16.0
├── WeLink@0.1.0
├── wd@1.14.0
├── WeLink@0.1.0 -> /usr/local/lib/node_modules/uitest
└── yargs@16.2.0
i think i've configured my automation envrionment correctly, but when i execute my script, i meet a problem:
`     Error: [setImplicitWaitTimeout(4000)] Error response status: 9, UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: Unhandled endpoint: /session/C61E87AC-5848-4557-8315-5F811B496900/timeouts/implicit_wait -- http://127.0.0.1:10100/ with parameters {
    wildcards =     (
        "session/C61E87AC-5848-4557-8315-5F811B496900/timeouts/implicit_wait"
    );
}
      at exports.newError (/Users/hwmeeting/uitest/node_modules/wd/lib/utils.js:152:13)
      at /Users/hwmeeting/uitest/node_modules/wd/lib/callbacks.js:36:19
      at /Users/hwmeeting/uitest/node_modules/wd/lib/webdriver.js:196:5
      at Request._callback (/Users/hwmeeting/uitest/node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (/Users/hwmeeting/uitest/node_modules/request/request.js:185:22)
      at Request.<anonymous> (/Users/hwmeeting/uitest/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (/Users/hwmeeting/uitest/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)`
need some help~~had anyone encountered the same problem as me?

**Comment by KazuCocoa** [comment]
It is because your client does not send W3C protocol.
If your `wd` was https://github.com/admc/wd, the client does not support W3C protocol fully. Please consider using another one like https://www.npmjs.com/package/selenium-webdriver or https://webdriver.io/.

This module follows W3C WebDriver protocol as README.
> The driver operates in scope of W3C WebDriver protocol with several custom extensions to cover operating-system specific scenarios.

**Comment by id0ma1no** [comment]
> It is because your client does not send W3C protocol.
> If your `wd` was https://github.com/admc/wd, the client does not support W3C protocol fully. Please consider using another one like https://www.npmjs.com/package/selenium-webdriver or https://webdriver.io/.
> 
> This module follows W3C WebDriver protocol as README.
> 
> > The driver operates in scope of W3C WebDriver protocol with several custom extensions to cover operating-system specific scenarios.

thx a lot，i'm trying to change my dependency from wd to selenium-webdriver and see if it works
