### ISSUE TITLE
Element cannot be found for native macOS app

### ISSUE THREAD

**Issue by SharpQ** [appium/appium-mac2-driver#74]
Hi, everyone!
Sorry if I'm being silly. I'm facing an issue when trying to find element by 'id' or 'accessibility id' each time getting 404 response. Also, for some reason, app elements can be located by Accessibility Inspector but not by Appium Inspector. I would be grateful for any advice.

Environment:
Appium v1.20.2
Xcode 12.4 (12D4e)
macOS Version 11.2.3 (Build 20D91)
Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
Application under test is native macOS (Cocoa/Foundation Kit + screens are created programmatically, storyboards not used)

Full logs:
https://gist.github.com/SharpQ/aec1440f0473b581d55c4a84191a7dbe

**Comment by mykola-mokhnach** [comment]
It could be that the page tree that XCTest consumes is different. Please attach the actual XML page source generated before the lookup is made.

**Comment by SharpQ** [comment]
Thanks for the quick reply! You can find XML page source here:
https://gist.github.com/SharpQ/44606e76cd50532a10cb25d248060112

Frankly speaking, I see none of the page elements I need.

**Comment by mykola-mokhnach** [comment]
If it is not visible in the page source then there is nothing we could do from Appium side. I would try to report it to Apple.
