### ISSUE TITLE
Execute javascript

### ISSUE THREAD

**Issue by sramssh** [appium/appium-mac2-driver#75]
I am working on Excel office-addin project. Addin is developed using office.js javascript api. For automation I am using mac2driver. I need to automate excel operations using office.js. Can I execute javascript using mac2driver? When I tried, it throws unhandled command exception. Any idea if the executeScript will be implemented for this driver?

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

Or

> Can I execute javascript using mac2driver?

Does this mean how to call JavaScript inside the app under test via mac2driver? Then, this driver does not support it. This driver can interact with elements that are available via XCTest framework.

**Comment by sramssh** [comment]
Thanks for the response! Yes, I am looking for a way to call Javascript inside the app under test via mac2driver.  Will something like be supported in future?

**Comment by KazuCocoa** [comment]
Perhaps no.
I don't know if https://developer.apple.com/documentation/xctest, which this driver used as the background, or private APIs can do such things. A possible way is that I guess WebView, but so far this driver does not have any plans to support WebView. I don't know this "WebView" is also the same as iOS's one though...

**Comment by HelenNeigel** [comment]
Are there any plans to implement similar to iOS solution for testing hybrid apps? The issue was opened in appium-mac-driver repo https://github.com/appium/appium-for-mac/issues/15. Are there any updates related to adopting XCTest Framework? Thanks.

**Comment by mykola-mokhnach** [comment]
Hybrid apps could be tested by using two drivers in a single test. Eventually, a web view is no different from a vanilla web browser, which could be automated using appropriate selenium webdriver. I don't see any major reasons in overcomplicating of the current mac2 driver implementation because of that.

**Comment by samsul-kabir-cihub** [comment]
@mykola-mokhnach could you please give an example of using such scenario. I am using mac application that uses frequently webview and I am stuck. I did research and I am not the only one who is having the same issue. so if you can share an example of your idea, that would be really helpful.

**Comment by samsul-kabir-cihub** [comment]
Hey @KazuCocoa thanks for the tips. I managed to have an work around finally. May be I will a document to help others who wants to test desktop app and switch between native and webview.
