### ISSUE TITLE
`arguments` not being passed on to process ?

### ISSUE THREAD

**Issue by gtalarico** [appium/appium-mac2-driver#78]
Hi and thank you for this project. 

I am trying to launch my macos with arguments.
I can launch from command line and it works, however when I launch from appium arguments are not being passed.

I have been stuck with an issue and wanted to check if this is not a known limitation or bug.
I have read all documentation and examples here https://github.com/appium/appium-mac2-driver/blob/master/README.md#capabilities.

Given `MyApp`:

I can launch from the command line and the process arguments are available as expected.
`arguments` has a full array including the `-state` arg.

```shell
~ /Users/gui_talarico/Library/Developer/Xcode/DerivedData/MyApp-fizalernvcuehkeshogbwjxczygc/Build/Products/Debug/MyApp\ Testing.app/Contents/MacOS/MyApp\ Testing \
    -state "/Users/user/dev/manual.json"
```

### With Appium

```python
caps = {
        "automationName": "mac2",
        "platformName": "mac",
        "bundleId": "com.company.MyApp.testing",
        "arguments": [
            "-state",
            "/Users/user/dev/manual.json",
        ],
    }

driver = webdriver.Remote(
            command_executor=self.APP_SERVER, desired_capabilities=caps
)
```

### Appium

Note `arguments` are received here.

```shell
[WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"version":"Version 11.3 (Build 20E232)"},"ready":true,"build":{"time":"May  5 2021 14:17:55"}},"sessionId":null}

[WebDriverAgentMac] The host process is ready within 7214ms

[WD Proxy] Matched '/session' to command name 'createSession'

[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:10100/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac",
"automationName":"mac2",
"bundleId":"com.company.MyApp.testing",
"arguments":["-state","/Users/user/dev/manual.json"]}}}

[WD Proxy] Got response with status 200: 
{"value":{"sessionId":"FB1360B8-823E-4860-A02A-A6CB4E4DB040","capabilities":{"CFBundleIdentifier":"com.company.MyApp.testing"}},
"sessionId":"FB1360B8-823E-4860-A02A-A6CB4E4DB040"}
```

However when I check/log the value of `ProcessInfo.processInfo.arguments` it's always only the application
 `/Users/gui_talarico/Library/Developer/Xcode/DerivedData/MyApp-fizalernvcuehkeshogbwjxczygc/Build/Products/Debug/MyApp\ Testing.app/Contents/MacOS/MyApp\ Testing` and does not include the args `-state`, etc. When I launch from cmd line the args show up as expected.

-----

### Update

Update - changed to `environment` and it's making through as expected! 🎉 
Am I missing anything from docs as far how "arguments" is supported?

```json
caps = { 
         ...,
        "environment": {
            "state": "/Users/user/dev/manual.json",
        },
        "arguments": [
            "-state",
            "/Users/user/dev/manual.json",
        ],
```

```swift
let args = ProcessInfo.processInfo.arguments
let env = ProcessInfo.processInfo.environment
let logger = Logger(subsystem: Bundle.main.bundleIdentifier!, category: "environment")
logger.log("XXX Args: \(args) ENV: \(env)")
```

Env values are present but arguments are not:
```
XXX Args: ["/Users/gui_talarico/Library/Developer/Xcode/DerivedData/MyApp-fizalernvcuehkeshogbwjxczygc/Build/Products/Debug/MyApp\ Testing.app/Contents/MacOS/MyApp\ Testing "] 
ENV: ["state": "/Users/user/dev/manual.json", <REDACTED> ]
```

**Comment by mykola-mokhnach** [comment]
Could that be an XCTest issue?
The logic for passing arguments lives in https://github.com/appium/appium-mac2-driver/blob/677be795849fb3efd6c6c5622c9b9e264d89b4fc/WebDriverAgentMac/WebDriverAgentLib/Commands/FBSessionCommands.m#L95 and I don't observe any issues there. Try to add some additional logging there to make sure `launchArguments` property is assigned properly

**Comment by mykola-mokhnach** [comment]
I was also observing the log message `Launching macOS application via NSWorkspace while sandboxed. Launch arguments and environment variables may be dropped.` in XCTest logs. Perhaps it has something to do with your issue

**Comment by gtalarico** [comment]
> Launching macOS application via NSWorkspace while sandboxed. Launch arguments and environment variables may be dropped.

My app is currently not sandbox, but I am not sure that's referring to my app or the webdriver agent. 
Either way, it's strange that `args` get dropped but `environment` variables are coming through OK.

I am new to mac/ios dev so this is a bit outside my area of expertise, unfortunately I don't think I will be very helpful in helping discover the issue here. I will close this, hopefully if someone more knowledgeable runs into this in the future they can build on top of this conversation.

Thank you so much for your willingness to help here @mykola-mokhnach . closing it for now to keep your issues clean 
but feel free to reopen if think its valuable

**Comment by mykola-mokhnach** [comment]
> Thank you so much for your willingness to help here @mykola-mokhnach . Closing it for now to keepissues clean
but feel free to reopen if think its valuable

np, you are welcome. I would try to launch the app with Apple Script and then  interact with it. You could use `prerun` capability or [macos: appleScript](https://github.com/appium/appium-mac2-driver#macos-applescript)
