### ISSUE TITLE
How to interact with System (Permission) Dialogs?

### ISSUE THREAD

**Issue by abeatte** [appium/appium-mac2-driver#79]
I have an app that requests permission to access the Camera and Microphone. This causes a system dialog to be presented. How can I have the driver interact with that dialog?

I have tried clicking on an arbitrary point on the screen using `/click` and passing in `{x: number, y: number}` but that end up clicking in an incorrect spot followed by crashing the runner. 

I have also tried spinning up the driver passing in the UserNotificationCenter bundleId (as that is the system service that presents the notification) but the driver is unable to even start when doing that (possibly due to access). 

Is there some sort of mode or feature that would allow this?

**Comment by mykola-mokhnach** [comment]
I assume it is an XCTest limitation. I would try to workaround it using AppleScript

**Comment by miksch123** [comment]
This can work, but only in certain circumstances. From past experience working with any type of permission prompt is a pain.
