### ISSUE TITLE
Enhancement Request: Add a possibility for running JXA snippets just like AppleScripts

### ISSUE THREAD

**Issue by sramssh** [appium/appium-mac2-driver#88]
Hi - I need a way to execute  macOS JXA (javascript for automation) just like there is a way to execute appleScript via executeScript("macos: appleScript", ImmutableMap.of("script", myScript));
Looks like it can be achieved by passing additional  language argument to osascript command like  "osascript -l JavaScript myscript".
I looked at this code file for applescript.js https://github.com/appium/appium-mac2-driver/blob/master/lib/commands/applescript.js.  Need exactly the same but with extra language argument  (as mentioned above).  
I would be happy to contribute to this project and add this enhancement, but need some instructions on how to compile the project, make code changes and test it. ( I am new to using macOS so just not there yet )

**Comment by mykola-mokhnach** [comment]
Thanks @sramssh 

Such change is not complicated: https://github.com/appium/appium-mac2-driver/pull/89
You are welcome to contribute to the project. Basically, it's quite simple to do the JS part of it: https://github.com/appium/appium-mac2-driver#development--testing

**Comment by sramssh** [comment]
@mykola-mokhnach  Thank you so much for jumping on it quickly and completing it! When will this be released?

**Comment by mykola-mokhnach** [comment]
It is already published to appium@beta
As for the general release - no idea. I don't decide it on my own.
