### ISSUE TITLE
Support for AXPath

### ISSUE THREAD

**Issue by raphaelschroiff** [appium/appium-mac2-driver#90]
Do you plan to add support for finding Elements via AXPath (e.g. /AXApplication[@AXTitle='Calculator']/AXWindow) ? 
We have have a hybrid (Mac native & WKWebView) App which we can automate with AXPath in the legacy mac driver but we would like to switch to mac2-driver to be future proof. With mac2-driver/XCUI XPath we cannot select the web content inside the WKWebView.

**Comment by mykola-mokhnach** [comment]
If the content is not reflected in the page source then it means XCTest does not fetch it. Only Apple could fix that.

**Comment by raphaelschroiff** [comment]
Thanks for the feedback, actually XCUITest is able to select the Elements in the WebView. But we choose to rather use  XCUITest directly, so this is not an issue for us.
