### ISSUE TITLE
How to get the attribute value of an element?

### ISSUE THREAD

**Issue by thinhndfloware** [appium/appium-mac2-driver#91]
Hi guys,

I've been using appium-mac2-driver + Python + selenium and impossible to get the value of an element's attribute. It showed an error that said the method is not implemented (see the attached screenshot).

As far as I know that the error is very clear and we have not supported it yet. A current solution from me is that I get page source and then find the element with all attributes. Could you please advise on another way to get the value of an element's attribute from a WebElement object?

Thank you so much.

![image](https://user-images.githubusercontent.com/67256035/129392376-eae33456-83ed-483e-ba5e-e7f84719822c.png)

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by thinhndfloware** [comment]
[Appium] Appium v1.21.0 creating new Mac2Driver (v0.13.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "mac",
[debug] [BaseDriver]     "appium:automationName": "mac2",
[debug] [BaseDriver]     "appium:newCommandTimeout": 30000,
[debug] [BaseDriver]     "appium:bundleId": "com.mycompany"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: ce5828fe-6b7f-48d7-812d-a2a372b6d683
[debug] [WebDriverAgentMac] Using bootstrap root: /usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac
[debug] [WebDriverAgentMac] Using xcodebuild binary at '/usr/bin/xcodebuild'
[WebDriverAgentMac] WebDriverAgent sources are up to date (1628736193669 >= 1628736193669)
[debug] [WebDriverAgentMac] Using 127.0.0.1 as server host
[debug] [WebDriverAgentMac] Using port 10100
[WebDriverAgentMac] The port #10100 at 127.0.0.1 is busy. Assuming it is an obsolete WDA server instance and trying to terminate it in order to start a new one
[WebDriverAgentMac] The previously running WDA server has been successfully terminated after 519ms
[WebDriverAgentMac] Mac2Driver host process logging is disabled. All the xcodebuild output is going to be suppressed. Set the 'showServerLogs' capability to 'true' if this is an undesired behavior
[WebDriverAgentMac] Starting Mac2Driver host process: xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentMac.xcodeproj -scheme WebDriverAgentRunner COMPILER_INDEX_STORE_ENABLE\=NO
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"version":"Version 10.15.7 (Build 19H114)"},"ready":true,"build":{"time":"Aug 13 2021 12:08:35"}},"sessionId":null}
[WebDriverAgentMac] The host process is ready within 3120ms
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:10100/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac","automationName":"mac2","newCommandTimeout":30000,"bundleId":"com.mycompany"}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7","capabilities":{"CFBundleIdentifier":"com.mycompany"}},"sessionId":"D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[Appium] New Mac2Driver session created successfully, session ce5828fe-6b7f-48d7-812d-a2a372b6d683 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1628959051699 (23:37:31 GMT+0700 (Indochina Time))
[debug] [W3C (ce5828fe)] Cached the protocol value 'W3C' for the new session ce5828fe-6b7f-48d7-812d-a2a372b6d683
[debug] [W3C (ce5828fe)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"mac","automationName":"mac2","newCommandTimeout":30000,"bundleId":"com.mycompany"}}
[HTTP] <-- POST /wd/hub/session 200 4807 ms - 182
[HTTP] 
[HTTP] --> POST /wd/hub/session/ce5828fe-6b7f-48d7-812d-a2a372b6d683/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeStaticText[@value=\"Sign Up\"]"}
[debug] [W3C (ce5828fe)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeStaticText[@value=\"Sign Up\"]","ce5828fe-6b7f-48d7-812d-a2a372b6d683"]
[debug] [BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:10100/session/D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7/element] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[@value=\"Sign Up\"]"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"D377D916-3244-46D3-ACF4-71D15EA0FDF5","element-6066-11e4-a52e-4f735466cecf":"D377D916-3244-46D3-ACF4-71D15EA0FDF5"},"sessionId":"D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7"}
[debug] [W3C (ce5828fe)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"D377D916-3244-46D3-ACF4-71D15EA0FDF5","ELEMENT":"D377D916-3244-46D3-ACF4-71D15EA0FDF5"}
[HTTP] <-- POST /wd/hub/session/ce5828fe-6b7f-48d7-812d-a2a372b6d683/element 200 432 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/ce5828fe-6b7f-48d7-812d-a2a372b6d683/execute/sync
[HTTP] {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsupported operation\";l[34...
[debug] [W3C (ce5828fe)] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsupported operation\";l[34]=\"move ...
[debug] [W3C (ce5828fe)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (ce5828fe)]     at Mac2Driver.execute (/usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/lib/commands/execute.js:38:9)
[debug] [W3C (ce5828fe)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [W3C (ce5828fe)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:137:12
[debug] [W3C (ce5828fe)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)
[debug] [W3C (ce5828fe)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)
[debug] [W3C (ce5828fe)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)
[debug] [W3C (ce5828fe)]     at Mac2Driver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [W3C (ce5828fe)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (ce5828fe)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [W3C (ce5828fe)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/ce5828fe-6b7f-48d7-812d-a2a372b6d683/execute/sync 405 66 ms - 1206
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/ce5828fe-6b7f-48d7-812d-a2a372b6d683
[HTTP] {}
[debug] [W3C (ce5828fe)] Calling AppiumDriver.deleteSession() with args: ["ce5828fe-6b7f-48d7-812d-a2a372b6d683"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1628959063284 (23:37:43 GMT+0700 (Indochina Time))
[Appium] Removing session ce5828fe-6b7f-48d7-812d-a2a372b6d683 from our master session list
[debug] [WD Proxy] Matched '/session/D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7] to [DELETE http://127.0.0.1:10100/session/D7CD1D6A-188F-4AB3-BB05-8A5A55614BC7] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1628959064326 (23:37:44 GMT+0700 (Indochina Time))
[debug] [W3C (ce5828fe)] Received response: null
[debug] [W3C (ce5828fe)] But deleting session, so not returning
[debug] [W3C (ce5828fe)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/ce5828fe-6b7f-48d7-812d-a2a372b6d683 200 1044 ms - 14

**Comment by KazuCocoa** [comment]
What client did you use? https://github.com/appium/python-client ?
It seems your client sent `{"script":"return (function(){return function(){var d=this;function f(a){return"string"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-` which works only for browser. It is not for Appium, so I guess you used vanilla selenium python client.

**Comment by thinhndfloware** [comment]
Thanks for your hint. I've corrected the import webdriver from the appium library (not from selenium). The issue is invalid now and I would like to close it.
