### ISSUE TITLE
How to install appium-mac2-driver?

### ISSUE THREAD

**Issue by aakrandan** [appium/appium-mac2-driver#94]
Sorry to ask such silly question, but i am not able to figure how to install this and use it with Appium application. It seems like this is framework. I am not able to understand how to use it with my python script. The Readme file says nothing about it.

**Comment by KazuCocoa** [comment]
Did you done https://github.com/appium/appium-mac2-driver#requirements and tried https://github.com/appium/appium-mac2-driver#examples after installing `appium`?

**Comment by aakrandan** [comment]
@KazuCocoa thanks for your response. Yes I had gone through those requirements, but the issue was that i was not understanding how to use it. But finally i figured it out. 

It seems like 'mac2Driver' is integrated with Appium v1.2 onwards, so i have to just import the 'webdriver' from Appium to use its APIs.

**Comment by KazuCocoa** [comment]
I guess you should learn appium itself first.
http://appium.io/docs/en/about-appium/intro/
http://appium.io/docs/en/drivers/mac2/

**Comment by aakrandan** [comment]
Yes, thank you will do that. I am new to this, so thank you for the links :)
