### ISSUE TITLE
mac2driver failed with Mac2Driver server is not listening error

### ISSUE THREAD

**Issue by xianenli30** [appium/appium-mac2-driver#95]
I'm new to the project and would absolutely like to set it up for some mac apps testing. 
I've been closely followed the readme example -https://github.com/appium/appium-mac2-driver#examples, gave accessibility to the xcode helper app, started appium listener and ran the example with `pytest` via console, but it didn't even start the session  properly and got the bellow error-

```
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. 
Original error: Mac2Driver server is not listening within 120000ms timeout. Try to increase the value of 'serverStartupTimeout' capability,
check the server logs and make sure the xcodebuild host process could be started manually from a terminal

../../Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py
```

Any advise is appreciated, been trying to look for an answer but no luck. Thanks!

**Comment by KazuCocoa** [comment]
Could you attach the full log as GIST?

**Comment by xianenli30** [comment]
@KazuCocoa Thanks for the quick attention, see attached log below:
[gistfile1.txt](https://github.com/appium/appium-mac2-driver/files/7220550/gistfile1.txt)

**Comment by mykola-mokhnach** [comment]
The attached file is not a server log. It is not very helpful

**Comment by xianenli30** [comment]
[server.txt](https://github.com/appium/appium-mac2-driver/files/7221296/server.txt)
@mykola-mokhnach Could you try take a look at this one?

**Comment by mykola-mokhnach** [comment]
> [WebDriverAgentMac] Mac2Driver host process logging is disabled. All the xcodebuild output is going to be suppressed. Set the 'showServerLogs' capability to 'true' if this is an undesired behavior
> [WebDriverAgentMac] Starting Mac2Driver host process: xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentMac.xcodeproj -scheme WebDriverAgentRunner COMPILER_INDEX_STORE_ENABLE\=NO
> [WebDriverAgentMac] Mac2Driver host process has exited with code 1, signal null

Please attach the log with `showServerLogs` capability enabled. Have you tried to run the xcodebuild command above manually?

**Comment by xianenli30** [comment]
ah..silly me, the test works now with xcodebuild run manually, thank you for the hint! @mykola-mokhnach
