### ISSUE TITLE
Cant get XPath 

### ISSUE THREAD

**Issue by kii-dot** [appium/appium-mac2-driver#98]
Hi, I'm using appium and appium for mac. I followed the instruction of pressing fn when hovering over the button of an app. But I can't seem to get the XPath. 

I followed the requirement and added xcodehelper to accessibility and also AppiumForMac

**Comment by k3ithl1m** [comment]
Thanks for quick response. Will get back to you on Monday. Entering a hackathon.

**Comment by poliveira-fuze** [comment]
How to use `appium-mac2-driver` to capture elements?

Should I run `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/Xcode Helper.app` then press `fn`?
