### ISSUE TITLE
macos: activateApp not implemented error

### ISSUE THREAD

**Issue by RedDevil91** [appium/appium-mac2-driver#99]
Hi!
We would like to use the Application Under Test Concept for automating some native tests on Mac using Appium and mac2-driver.
We started the driver without bundleId and then tried to use activateApp but in vain. The error say it's not yet implemented:

`[debug] [W3C (1eed6dce)] Calling AppiumDriver.activateApp() with args: ["com.apple.calculator",null,null,null,"1eed6dce-93bb-4a53-a9fd-68d0468dc1bf"]`

`[debug] [W3C (1eed6dce)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented`

`[debug] [W3C (1eed6dce)]     at Mac2Driver.executeCommand (/Users/gberta/.nvm/versions/node/v14.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:328:13)`

`[debug] [W3C (1eed6dce)]     at AppiumDriver.executeCommand (/Users/gberta/.nvm/versions/node/v14.15.0/lib/node_modules/appium/lib/appium.js:563:36)`

`[debug] [W3C (1eed6dce)]     at runMicrotasks (<anonymous>)`

`[debug] [W3C (1eed6dce)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)`

`[debug] [W3C (1eed6dce)]     at asyncHandler (/Users/gberta/.nvm/versions/node/v14.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)`

Are you aware of this problem?

**Comment by rmarinho** [comment]
Can we just implement this instead? so it s similar to use other platforms? 

Should be as easy as map `AppiumDriver.activateApp()`  to `driver.execute_script("macos: activateApp", {"bundleId": "com.apple.calculator"})`

Or is this something to be done in other repo?
